import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import hp from "../public/hp.png";
import sp from "../public/sp.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import pp from "../public/pp.png";
import c from "../public/c.png";
import py from "../public/py.png";
import js from "../public/js.png";
import sw from "../public/sw.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Skanda Nagaraja Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">SkandaNagraja</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://resume.io/r/aoQAtnL8j" target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Skanda Nagaraja
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              CS Student @ Texas A&M.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Motivated computer science student passionate about machine learning and artificial intelligence. Seeking dynamic opportunities to apply theoretical knowledge and enhance practical skills in the ML/AI field. Eager to contribute to cutting-edge projects, collaborate with industry professionals, and continuously expand expertise in this rapidly evolving domain.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              
              <a href="https://www.linkedin.com/in/skanda-nagaraja-84b9471a6/" target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Skanda0147?tab=projects" target="_blank">
                <AiFillGithub />
              </a>
              
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={pp} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Skills
            </h2>

          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={c} width={100} height={100} />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={js} width={100} height={100} />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={sw} width={100} height={100} />
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={py} width={100} height={100} />
            </div>
          </div>
        </section>
       
        <section className="py-10">
          <div>
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Projects
            </h2>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Driven computer science student specializing in deep learning and python libraries, adept at developing innovative projects in the field. Demonstrated expertise in leveraging cutting-edge technologies to build impactful products, utilizing frameworks such as TensorFlow and PyTorch. Passionate about creating practical solutions, consistently striving to stay updated with the latest advancements in deep learning methodologies and tools.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                title = "Housing price prediction in the Bay Area"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={hp}
                
              />
              <div className="text-center">
                <h3 className="text-2xl py-1 dark:text-white ">Housing Price Prediction</h3>
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Developed a deep learning model to predict the housing prices in the Bay Area using historical data. The model was trained on 20 years of data and achieved an accuracy of 94%.
                </p>
              </div>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                title="S&P 500 Stock Price Prediction"
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={sp}
                                
              />
              <div className="text-center">
                <h3 className="text-2xl py-1 dark:text-white ">S&P 500 Stock Price Prediction</h3>
                <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Developed a deep learning model to predict the stock price of the S&P 500 index using historical data. The model achieved an accuracy of 98%.
                </p>
              </div>

            </div>
            
        
          </div>
        </section>
      </main>
    </div>
  );
}
